apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nic-repo-seventytwo
  description: nic-repo-seventytwo
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:default/mantechidp285users
  lifecycle: experimental
